### ISSUE TITLE
Is There a Forum or Group Where I Can Ask Questions About This Notepad Program?

### ISSUE THREAD

**Issue by SweetProductDeals** [alexkdeveloper/notepad#18]
Is there a forum or group available for this outstanding basic notepad program where a person can ask questions?  I realize this is not a software issue but I didn't know where else to ask?  I hope that is fine.  I'm trying to figure out  how to backup my notes so I don't lost them when the system crashes eventually.  Thank you.

**Comment by alexkdeveloper** [comment]
As far as I know, there are no such groups or forums.

The program stores notes here:
/home/user-name/.var/app/com.github.alexkdeveloper.notepad/data/notes_for_notepad_app

You can copy the notes that are important to you and save them in your cloud or on an external media.

By the way, some cloud storages support synchronization and can automatically download files from selected folders.

**Comment by begin-theadventure** [comment]
`~/.local/share/notes_for_notepad_app` for system installation.

**Comment by SweetProductDeals** [comment]
That's exactly what I wanted to know.  Thank you very much.

Timothy G. Slazyk
***@***.***
716-579-7522

This is your opportunity to stock up on food!
You know it's the right thing to do, so why
do you keep putting it off until another day?
I've done my research and this is the best
supplier of food with a 25 year shelf life.
<https://mypatriotsupply.com/?rfsn=4154786.08bd2e>
John 8:45 - Read "Mathew," "Mark," "Luke," "John," and "Revelation." There
are Tremendous Blessings For Doing So.

*"And because I tell you the truth, ye believe me not."*
*King James Bible 1611 <https://www.kingjamesbibleonline.org/>*
